- hosts: all
  become: yes
  user: ec2-user
  gather_facts: no
  pre_tasks:
    - name: 'atualizando o repo'
      raw: 'apt update'
    - name: 'instalando o python'
      raw: 'apt install -y python'
  roles: 
  - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: ec2-user
  roles:
  - { role: create_cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: ec2-user
  roles:
  - { role: join_workers, tags: ["join_workers_role"] }

