- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'atualizando o repo'
      raw: 'apt update'
    - name: 'instalando o python'
      raw: 'apt install -y python'
  roles: 
    - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  roles:
    - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  roles:
    - { role: join-workers, tags: ["join_workers_role"] }