---
- name: check environment
  assert:
    that:
      - url_prometheus is defined
      - deploy_prometheus is defined
    msg: "Erro na definição de variáveis"

- name: helm add repo prometheus-community
  shell: helm repo add prometheus-community {{ url_prometheus }}
  register: prometheus_add_repo

- name: helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: instalando o kube-prometheus-stack
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install
