---
- name: check environment
  assert:
    that:
      - url_heml is defined
      - tmp_helm_install_sh is defined
    msg: "Erro na definição de variáveis"

- name: Download helm
  get_url:
    url: "{{ url_heml }}"
    dest: "{{ tmp_helm_install_sh }}"
    mode: 0775
  ignore_errors: true
  register: download

- name: Instalando Helm
  shell:
    "{{ tmp_helm_install_sh }}"
  when:
    - download.failed|bool == false
  register: install_helm

- name:
  debug: var=install_helm

## Instalação do help via pacote apt

# - name: check environment
#   assert:
#     that:
#       - url_repo_help is defined
#       - repo_helm is defined
#     msg: "Erro na definição de variáveis"

# - name: installar apt-transport-https
#   apt:
#     name: apt-transport-https
#     state: latest

# - name: adicionando as chaves do repo apt do helm
#   apt_key:
#     url: "{{ url_repo_help }}"
#     state: present

# - name: adicionando repo do helm
#   apt_repository:
#     repo: "{{ repo_helm }}"
#     state: present
#     update_cache: yes

# - name: instalando helm via apt
#   apt:
#     name: helm
#     state: latest
#     update_cache: yes